// import { Background } from './Background';
export const LoaderConfig = {
    Background:  "src/sprites/Background.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed :  "/src/sprites/ButtonAutoSpinHover_1.png",
    BetPanel :  "/src/sprites/PanelTotalBet.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/PanelLines.png",
    winPanel :  "/src/sprites/PanelWin.png",    
    balancePanel :  "/src/sprites/PanelBalance.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",
    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButtonHover.png",
    disconnectClose: "src/sprites/disconnectClose.png",
    popupBgimg: "src/sprites/AboutPanel.png",
    logoutPop: "src/sprites/logoutPop.png",
    normalButton: "src/sprites/NormalButton.png",
    bigWinPopup: "src/sprites/BigWinPopup.png",
    hugeWinPopup:"src/sprites/HugeWinPopup.png",
    megaWin: "src/sprites/MegaWin.png",
    jackpotPopup: "src/sprites/jackpotPopup.png",
    freeSpinPopup: "src/sprites/FreeSpinPopup.png",
    freeSpinStartButton: "src/sprites/freeSpinStartButton.png",
    freeSpinStartButtonPressed: "src/sprites/SpinButtonPressed.png",
    spinCircle: "src/sprites/SpinCircle.png",
    spinCenter: "src/sprites/SpinCenter.png",
    wheelBg: "src/sprites/WheelBg.png",

    logo: "src/sprites/vikingsLogo.png",
    assetsloader: "src/sprites/assetsLoader.png",
    loaderBg: "src/sprites/loaderBg.png",
    stairs: "src/sprites/Stair.jpg",
    reelBg: "src/sprites/reelBg.png",   
    column: "src/sprites/columnLeft.png",
    snow: "src/sprites/Snow.png",
    roof:"src/sprites/Roof.png",
    winLine: "src/sprites/WinLine.png",
    lineSymbols: "src/sprites/LineSymbols.png",
    settingPopup:"src/sprites/settingPopup.png",
    soundImage:"src/sprites/Sounds.png",
    musicImage: "src/sprites/Music.png",
    toggleBar: "src/sprites/ToggleBar.png",
    onButton: "src/sprites/On.png",
    offButton: "src/sprites/Off.png",
    headingImage: "src/sprites/PayTable_.png",
    popupbackgroumdImage: "src/sprites/popupbackgroumdImage.jpg",
    scrollBg: "src/sprites/ScrollBar.png",
    scroller:"src/sprites/Roller.png",
    minorSymbolsHeading: "src/sprites/MoniorSymbols.png",
    majorSymbolHeading: "src/sprites/MajorSymbolsHeading.png",
    specialSymBolHeading: "src/sprites/SpecialSymbolHeading.png",
    payLines: "src/sprites/PayLines.png",
    
    slots3_0 :  "/src/sprites/Symbols/runeOthala/RuneOthala 01.png",
    slots3_1 :  "/src/sprites/Symbols/runeOthala/RuneOthala 02.png",
    slots3_2 :  "/src/sprites/Symbols/runeOthala/RuneOthala 03.png",
    slots3_3 :  "/src/sprites/Symbols/runeOthala/RuneOthala 04.png",
    slots3_4 :  "/src/sprites/Symbols/runeOthala/RuneOthala 05.png",
    slots3_5 :  "/src/sprites/Symbols/runeOthala/RuneOthala 06.png",
    slots3_6 :  "/src/sprites/Symbols/runeOthala/RuneOthala 07.png",
    slots3_7 :  "/src/sprites/Symbols/runeOthala/RuneOthala 08.png",
    slots3_8 :  "/src/sprites/Symbols/runeOthala/RuneOthala 09.png",
    slots3_9 :  "/src/sprites/Symbols/runeOthala/RuneOthala 10.png",
    slots3_10:  "/src/sprites/Symbols/runeOthala/RuneOthala 11.png",
    slots3_11:  "/src/sprites/Symbols/runeOthala/RuneOthala 12.png",
    slots3_12:  "/src/sprites/Symbols/runeOthala/RuneOthala 13.png",
    slots3_13:  "/src/sprites/Symbols/runeOthala/RuneOthala 14.png",
    slots3_14:  "/src/sprites/Symbols/runeOthala/RuneOthala 15.png",
    slots3_15:  "/src/sprites/Symbols/runeOthala/RuneOthala 16.png",
    slots3_16:  "/src/sprites/Symbols/runeOthala/RuneOthala 17.png",
    slots3_17:  "/src/sprites/Symbols/runeOthala/RuneOthala 18.png",
    slots3_18:  "/src/sprites/Symbols/runeOthala/RuneOthala 19.png",
    slots3_19:  "/src/sprites/Symbols/runeOthala/RuneOthala 20.png",
    slots3_20:  "/src/sprites/Symbols/runeOthala/RuneOthala 21.png",
    slots3_21:  "/src/sprites/Symbols/runeOthala/RuneOthala 22.png",
    slots3_22:  "/src/sprites/Symbols/runeOthala/RuneOthala 23.png",
    slots3_23:  "/src/sprites/Symbols/runeOthala/RuneOthala 24.png",

    slots4_0 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 01.png",
    slots4_1 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 02.png",
    slots4_2 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 03.png",
    slots4_3 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 04.png",
    slots4_4 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 05.png",
    slots4_5 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 06.png",
    slots4_6 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 07.png",
    slots4_7 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 08.png",
    slots4_8 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 09.png",
    slots4_9 :  "/src/sprites/Symbols/runeRaidho/RuneRaidho 10.png",
    slots4_10:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 11.png",
    slots4_11:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 12.png",
    slots4_12:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 13.png",
    slots4_13:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 14.png",
    slots4_14:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 15.png",
    slots4_15:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 16.png",
    slots4_16:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 17.png",
    slots4_17:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 18.png",
    slots4_18:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 19.png",
    slots4_19:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 20.png",
    slots4_20:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 21.png",
    slots4_21:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 22.png",
    slots4_22:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 23.png",
    slots4_23:  "/src/sprites/Symbols/runeRaidho/RuneRaidho 24.png",

    slots1_0 :  "/src/sprites/Symbols/runeGebo/RuneGebo 01.png",
    slots1_1 :  "/src/sprites/Symbols/runeGebo/RuneGebo 02.png",
    slots1_2 :  "/src/sprites/Symbols/runeGebo/RuneGebo 03.png",
    slots1_3 :  "/src/sprites/Symbols/runeGebo/RuneGebo 04.png",
    slots1_4 :  "/src/sprites/Symbols/runeGebo/RuneGebo 05.png",
    slots1_5 :  "/src/sprites/Symbols/runeGebo/RuneGebo 06.png",
    slots1_6 :  "/src/sprites/Symbols/runeGebo/RuneGebo 07.png",
    slots1_7 :  "/src/sprites/Symbols/runeGebo/RuneGebo 08.png",
    slots1_8 :  "/src/sprites/Symbols/runeGebo/RuneGebo 09.png",
    slots1_9 :  "/src/sprites/Symbols/runeGebo/RuneGebo 10.png",
    slots1_10:  "/src/sprites/Symbols/runeGebo/RuneGebo 11.png",
    slots1_11:  "/src/sprites/Symbols/runeGebo/RuneGebo 12.png",
    slots1_12:  "/src/sprites/Symbols/runeGebo/RuneGebo 13.png",
    slots1_13:  "/src/sprites/Symbols/runeGebo/RuneGebo 14.png",
    slots1_14:  "/src/sprites/Symbols/runeGebo/RuneGebo 15.png",
    slots1_15:  "/src/sprites/Symbols/runeGebo/RuneGebo 16.png",
    slots1_16:  "/src/sprites/Symbols/runeGebo/RuneGebo 17.png",
    slots1_17:  "/src/sprites/Symbols/runeGebo/RuneGebo 18.png",
    slots1_18:  "/src/sprites/Symbols/runeGebo/RuneGebo 19.png",
    slots1_19:  "/src/sprites/Symbols/runeGebo/RuneGebo 20.png",
    slots1_20:  "/src/sprites/Symbols/runeGebo/RuneGebo 21.png",
    slots1_21:  "/src/sprites/Symbols/runeGebo/RuneGebo 22.png",
    slots1_22:  "/src/sprites/Symbols/runeGebo/RuneGebo 23.png",
    slots1_23:  "/src/sprites/Symbols/runeGebo/RuneGebo 24.png",
    
    slots0_0 :  "/src/sprites/Symbols/runeFehu/RuneFehu 01.png",
    slots0_1 :  "/src/sprites/Symbols/runeFehu/RuneFehu 02.png",
    slots0_2 :  "/src/sprites/Symbols/runeFehu/RuneFehu 03.png",
    slots0_3 :  "/src/sprites/Symbols/runeFehu/RuneFehu 04.png",
    slots0_4 :  "/src/sprites/Symbols/runeFehu/RuneFehu 05.png",
    slots0_5 :  "/src/sprites/Symbols/runeFehu/RuneFehu 06.png",
    slots0_6 :  "/src/sprites/Symbols/runeFehu/RuneFehu 07.png",
    slots0_7 :  "/src/sprites/Symbols/runeFehu/RuneFehu 08.png",
    slots0_8 :  "/src/sprites/Symbols/runeFehu/RuneFehu 09.png",
    slots0_9 :  "/src/sprites/Symbols/runeFehu/RuneFehu 10.png",
    slots0_10:  "/src/sprites/Symbols/runeFehu/RuneFehu 11.png",
    slots0_11:  "/src/sprites/Symbols/runeFehu/RuneFehu 12.png",
    slots0_12:  "/src/sprites/Symbols/runeFehu/RuneFehu 13.png",
    slots0_13:  "/src/sprites/Symbols/runeFehu/RuneFehu 14.png",
    slots0_14:  "/src/sprites/Symbols/runeFehu/RuneFehu 15.png",
    slots0_15:  "/src/sprites/Symbols/runeFehu/RuneFehu 16.png",
    slots0_16:  "/src/sprites/Symbols/runeFehu/RuneFehu 17.png",
    slots0_17:  "/src/sprites/Symbols/runeFehu/RuneFehu 18.png",
    slots0_18:  "/src/sprites/Symbols/runeFehu/RuneFehu 19.png",
    slots0_19:  "/src/sprites/Symbols/runeFehu/RuneFehu 20.png",
    slots0_20:  "/src/sprites/Symbols/runeFehu/RuneFehu 21.png",
    slots0_21:  "/src/sprites/Symbols/runeFehu/RuneFehu 22.png",
    slots0_22:  "/src/sprites/Symbols/runeFehu/RuneFehu 23.png",
    slots0_23:  "/src/sprites/Symbols/runeFehu/RuneFehu 24.png",

    slots2_0 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 01.png",
    slots2_1 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 02.png",
    slots2_2 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 03.png",
    slots2_3 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 04.png",
    slots2_4 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 05.png",
    slots2_5 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 06.png",
    slots2_6 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 07.png",
    slots2_7 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 08.png",
    slots2_8 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 09.png",
    slots2_9 :  "/src/sprites/Symbols/runeMannaz/RuneMannaz 10.png",
    slots2_10:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 11.png",
    slots2_11:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 12.png",
    slots2_12:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 13.png",
    slots2_13:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 14.png",
    slots2_14:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 15.png",
    slots2_15:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 16.png",
    slots2_16:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 17.png",
    slots2_17:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 18.png",
    slots2_18:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 19.png",
    slots2_19:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 20.png",
    slots2_20:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 21.png",
    slots2_21:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 22.png",
    slots2_22:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 23.png",
    slots2_23:  "/src/sprites/Symbols/runeMannaz/RuneMannaz 24.png",

    slots6_0 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 01.png",
    slots6_1 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 02.png",
    slots6_2 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 03.png",
    slots6_3 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 04.png",
    slots6_4 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 05.png",
    slots6_5 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 06.png",
    slots6_6 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 07.png",
    slots6_7 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 08.png",
    slots6_8 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 09.png",
    slots6_9 :  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 10.png",
    slots6_10:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 11.png",
    slots6_11:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 12.png",
    slots6_12:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 13.png",
    slots6_13:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 14.png",
    slots6_14:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 15.png",
    slots6_15:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 16.png",
    slots6_16:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 17.png",
    slots6_17:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 18.png",
    slots6_18:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 19.png",
    slots6_19:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 20.png",
    slots6_20:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 21.png",
    slots6_21:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 22.png",
    slots6_22:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 23.png",
    slots6_23:  "/src/sprites/Symbols/BlondyGirl/MajorBlondyGirl 24.png",

    slots5_0 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 01.png",
    slots5_1 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 02.png",
    slots5_2 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 03.png",
    slots5_3 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 04.png",
    slots5_4 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 05.png",
    slots5_5 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 06.png",
    slots5_6 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 07.png",
    slots5_7 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 08.png",
    slots5_8 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 09.png",
    slots5_9 :  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 10.png",
    slots5_10:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 11.png",
    slots5_11:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 12.png",
    slots5_12:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 13.png",
    slots5_13:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 14.png",
    slots5_14:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 15.png",
    slots5_15:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 16.png",
    slots5_16:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 17.png",
    slots5_17:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 18.png",
    slots5_18:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 19.png",
    slots5_19:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 20.png",
    slots5_20:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 21.png",
    slots5_21:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 22.png",
    slots5_22:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 23.png",
    slots5_23:  "/src/sprites/Symbols/BlondeMan/MajorBlondeMan 24.png",

    slots7_0 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 01.png",
    slots7_1 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 02.png",
    slots7_2 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 03.png",
    slots7_3 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 04.png",
    slots7_4 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 05.png",
    slots7_5 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 06.png",
    slots7_6 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 07.png",
    slots7_7 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 08.png",
    slots7_8 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 09.png",
    slots7_9 :  "/src/sprites/Symbols/DarkMan/MajorDarkMan 10.png",
    slots7_10:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 11.png",
    slots7_11:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 12.png",
    slots7_12:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 13.png",
    slots7_13:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 14.png",
    slots7_14:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 15.png",
    slots7_15:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 16.png",
    slots7_16:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 17.png",
    slots7_17:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 18.png",
    slots7_18:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 19.png",
    slots7_19:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 20.png",
    slots7_20:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 21.png",
    slots7_21:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 22.png",
    slots7_22:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 23.png",
    slots7_23:  "/src/sprites/Symbols/DarkMan/MajorDarkMan 24.png",

    slots8_0 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 01.png",
    slots8_1 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 02.png",
    slots8_2 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 03.png",
    slots8_3 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 04.png",
    slots8_4 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 05.png",
    slots8_5 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 06.png",
    slots8_6 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 07.png",
    slots8_7 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 08.png",
    slots8_8 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 09.png",
    slots8_9 :  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 10.png",
    slots8_10:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 11.png",
    slots8_11:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 12.png",
    slots8_12:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 13.png",
    slots8_13:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 14.png",
    slots8_14:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 15.png",
    slots8_15:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 16.png",
    slots8_16:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 17.png",
    slots8_17:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 18.png",
    slots8_18:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 19.png",
    slots8_19:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 20.png",
    slots8_20:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 21.png",
    slots8_21:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 22.png",
    slots8_22:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 23.png",
    slots8_23:  "/src/sprites/Symbols/GingerGirl/MajorGingerGirl 24.png",

    slots11_0 :  "/src/sprites/Symbols/Scatter/Scatter 01.png",
    slots11_1 :  "/src/sprites/Symbols/Scatter/Scatter 02.png",
    slots11_2 :  "/src/sprites/Symbols/Scatter/Scatter 03.png",
    slots11_3 :  "/src/sprites/Symbols/Scatter/Scatter 04.png",
    slots11_4 :  "/src/sprites/Symbols/Scatter/Scatter 05.png",
    slots11_5 :  "/src/sprites/Symbols/Scatter/Scatter 06.png",
    slots11_6 :  "/src/sprites/Symbols/Scatter/Scatter 07.png",
    slots11_7 :  "/src/sprites/Symbols/Scatter/Scatter 08.png",
    slots11_8 :  "/src/sprites/Symbols/Scatter/Scatter 09.png",
    slots11_9 :  "/src/sprites/Symbols/Scatter/Scatter 10.png",
    slots11_10:  "/src/sprites/Symbols/Scatter/Scatter 11.png",
    slots11_11:  "/src/sprites/Symbols/Scatter/Scatter 12.png",
    slots11_12:  "/src/sprites/Symbols/Scatter/Scatter 13.png",
    slots11_13:  "/src/sprites/Symbols/Scatter/Scatter 14.png",
    slots11_14:  "/src/sprites/Symbols/Scatter/Scatter 15.png",
    slots11_15:  "/src/sprites/Symbols/Scatter/Scatter 16.png",
    slots11_16:  "/src/sprites/Symbols/Scatter/Scatter 17.png",
    slots11_17:  "/src/sprites/Symbols/Scatter/Scatter 18.png",
    slots11_18:  "/src/sprites/Symbols/Scatter/Scatter 19.png",
    slots11_19:  "/src/sprites/Symbols/Scatter/Scatter 20.png",
    slots11_20:  "/src/sprites/Symbols/Scatter/Scatter 21.png",
    slots11_21:  "/src/sprites/Symbols/Scatter/Scatter 22.png",
    slots11_22:  "/src/sprites/Symbols/Scatter/Scatter 23.png",
    slots11_23:  "/src/sprites/Symbols/Scatter/Scatter 24.png",
    slots11_24:  "/src/sprites/Symbols/Scatter/Scatter 25.png",
    slots11_25:  "/src/sprites/Symbols/Scatter/Scatter 26.png",
    slots11_26:  "/src/sprites/Symbols/Scatter/Scatter 27.png",
    slots11_27:  "/src/sprites/Symbols/Scatter/Scatter 28.png",
    slots11_28:  "/src/sprites/Symbols/Scatter/Scatter 29.png",
    slots11_29:  "/src/sprites/Symbols/Scatter/Scatter 30.png",
    slots11_30:  "/src/sprites/Symbols/Scatter/Scatter 31.png",
    slots11_31:  "/src/sprites/Symbols/Scatter/Scatter 32.png",
    slots11_32:  "/src/sprites/Symbols/Scatter/Scatter 33.png",
    slots11_33:  "/src/sprites/Symbols/Scatter/Scatter 34.png",
    slots11_34:  "/src/sprites/Symbols/Scatter/Scatter 35.png",
    slots11_35:  "/src/sprites/Symbols/Scatter/Scatter 36.png",

    slots9_0 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 01.png",
    slots9_1 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 02.png",
    slots9_2 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 03.png",
    slots9_3 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 04.png",
    slots9_4 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 05.png",
    slots9_5 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 06.png",
    slots9_6 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 07.png",
    slots9_7 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 08.png",
    slots9_8 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 09.png",
    slots9_9 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 10.png",
    slots9_10:  "/src/sprites/Symbols/FreeSpins/FreeSpins 11.png",
    slots9_11:  "/src/sprites/Symbols/FreeSpins/FreeSpins 12.png",
    slots9_12:  "/src/sprites/Symbols/FreeSpins/FreeSpins 13.png",
    slots9_13:  "/src/sprites/Symbols/FreeSpins/FreeSpins 14.png",
    slots9_14:  "/src/sprites/Symbols/FreeSpins/FreeSpins 15.png",
    slots9_15:  "/src/sprites/Symbols/FreeSpins/FreeSpins 16.png",
    slots9_16:  "/src/sprites/Symbols/FreeSpins/FreeSpins 17.png",
    slots9_17:  "/src/sprites/Symbols/FreeSpins/FreeSpins 18.png",
    slots9_18:  "/src/sprites/Symbols/FreeSpins/FreeSpins 19.png",
    slots9_19:  "/src/sprites/Symbols/FreeSpins/FreeSpins 20.png",
    slots9_20:  "/src/sprites/Symbols/FreeSpins/FreeSpins 21.png",
    slots9_21:  "/src/sprites/Symbols/FreeSpins/FreeSpins 22.png",
    slots9_22:  "/src/sprites/Symbols/FreeSpins/FreeSpins 23.png",
    slots9_23:  "/src/sprites/Symbols/FreeSpins/FreeSpins 24.png",
    slots9_24:  "/src/sprites/Symbols/FreeSpins/FreeSpins 25.png",
    slots9_25:  "/src/sprites/Symbols/FreeSpins/FreeSpins 26.png",
    slots9_26:  "/src/sprites/Symbols/FreeSpins/FreeSpins 27.png",
    slots9_27:  "/src/sprites/Symbols/FreeSpins/FreeSpins 28.png",
    slots9_28:  "/src/sprites/Symbols/FreeSpins/FreeSpins 29.png",
    slots9_29:  "/src/sprites/Symbols/FreeSpins/FreeSpins 30.png",
    slots9_30:  "/src/sprites/Symbols/FreeSpins/FreeSpins 31.png",
    slots9_31:  "/src/sprites/Symbols/FreeSpins/FreeSpins 32.png",
    slots9_32:  "/src/sprites/Symbols/FreeSpins/FreeSpins 33.png",
    slots9_33:  "/src/sprites/Symbols/FreeSpins/FreeSpins 34.png",
    slots9_34:  "/src/sprites/Symbols/FreeSpins/FreeSpins 35.png",
    slots9_35:  "/src/sprites/Symbols/FreeSpins/FreeSpins 36.png",

    slots13_0 :  "/src/sprites/Symbols/Bonus/Bonus 01.png",
    slots13_1 :  "/src/sprites/Symbols/Bonus/Bonus 02.png",
    slots13_2 :  "/src/sprites/Symbols/Bonus/Bonus 03.png",
    slots13_3 :  "/src/sprites/Symbols/Bonus/Bonus 04.png",
    slots13_4 :  "/src/sprites/Symbols/Bonus/Bonus 05.png",
    slots13_5 :  "/src/sprites/Symbols/Bonus/Bonus 06.png",
    slots13_6 :  "/src/sprites/Symbols/Bonus/Bonus 07.png",
    slots13_7 :  "/src/sprites/Symbols/Bonus/Bonus 08.png",
    slots13_8 :  "/src/sprites/Symbols/Bonus/Bonus 09.png",
    slots13_9 :  "/src/sprites/Symbols/Bonus/Bonus 10.png",
    slots13_10:  "/src/sprites/Symbols/Bonus/Bonus 11.png",
    slots13_11:  "/src/sprites/Symbols/Bonus/Bonus 12.png",
    slots13_12:  "/src/sprites/Symbols/Bonus/Bonus 13.png",
    slots13_13:  "/src/sprites/Symbols/Bonus/Bonus 14.png",
    slots13_14:  "/src/sprites/Symbols/Bonus/Bonus 15.png",
    slots13_15:  "/src/sprites/Symbols/Bonus/Bonus 16.png",
    slots13_16:  "/src/sprites/Symbols/Bonus/Bonus 17.png",
    slots13_17:  "/src/sprites/Symbols/Bonus/Bonus 18.png",
    slots13_18:  "/src/sprites/Symbols/Bonus/Bonus 19.png",
    slots13_19:  "/src/sprites/Symbols/Bonus/Bonus 20.png",
    slots13_20:  "/src/sprites/Symbols/Bonus/Bonus 21.png",
    slots13_21:  "/src/sprites/Symbols/Bonus/Bonus 22.png",
    slots13_22:  "/src/sprites/Symbols/Bonus/Bonus 23.png",
    slots13_23:  "/src/sprites/Symbols/Bonus/Bonus 24.png",
    slots13_24:  "/src/sprites/Symbols/Bonus/Bonus 25.png",
    slots13_25:  "/src/sprites/Symbols/Bonus/Bonus 26.png",
    slots13_26:  "/src/sprites/Symbols/Bonus/Bonus 27.png",
    slots13_27:  "/src/sprites/Symbols/Bonus/Bonus 28.png",
    slots13_28:  "/src/sprites/Symbols/Bonus/Bonus 29.png",
    slots13_29:  "/src/sprites/Symbols/Bonus/Bonus 30.png",
    slots13_30:  "/src/sprites/Symbols/Bonus/Bonus 31.png",
    slots13_31:  "/src/sprites/Symbols/Bonus/Bonus 32.png",
    slots13_32:  "/src/sprites/Symbols/Bonus/Bonus 33.png",
    slots13_33:  "/src/sprites/Symbols/Bonus/Bonus 34.png",
    slots13_34:  "/src/sprites/Symbols/Bonus/Bonus 35.png",
    slots13_35:  "/src/sprites/Symbols/Bonus/Bonus 36.png",

    slots10_0 :  "/src/sprites/Symbols/Wild/Wild 01.png",
    slots10_1 :  "/src/sprites/Symbols/Wild/Wild 02.png",
    slots10_2 :  "/src/sprites/Symbols/Wild/Wild 03.png",
    slots10_3 :  "/src/sprites/Symbols/Wild/Wild 04.png",
    slots10_4 :  "/src/sprites/Symbols/Wild/Wild 05.png",
    slots10_5 :  "/src/sprites/Symbols/Wild/Wild 06.png",
    slots10_6 :  "/src/sprites/Symbols/Wild/Wild 07.png",
    slots10_7 :  "/src/sprites/Symbols/Wild/Wild 08.png",
    slots10_8 :  "/src/sprites/Symbols/Wild/Wild 09.png",
    slots10_9 :  "/src/sprites/Symbols/Wild/Wild 10.png",
    slots10_10:  "/src/sprites/Symbols/Wild/Wild 11.png",
    slots10_11:  "/src/sprites/Symbols/Wild/Wild 12.png",
    slots10_12:  "/src/sprites/Symbols/Wild/Wild 13.png",
    slots10_13:  "/src/sprites/Symbols/Wild/Wild 14.png",
    slots10_14:  "/src/sprites/Symbols/Wild/Wild 15.png",
    slots10_15:  "/src/sprites/Symbols/Wild/Wild 16.png",
    slots10_16:  "/src/sprites/Symbols/Wild/Wild 17.png",
    slots10_17:  "/src/sprites/Symbols/Wild/Wild 18.png",
    slots10_18:  "/src/sprites/Symbols/Wild/Wild 19.png",
    slots10_19:  "/src/sprites/Symbols/Wild/Wild 20.png",
    slots10_20:  "/src/sprites/Symbols/Wild/Wild 21.png",
    slots10_21:  "/src/sprites/Symbols/Wild/Wild 22.png",
    slots10_22:  "/src/sprites/Symbols/Wild/Wild 23.png",
    slots10_23:  "/src/sprites/Symbols/Wild/Wild 24.png",
    slots10_24:  "/src/sprites/Symbols/Wild/Wild 25.png",
    slots10_25:  "/src/sprites/Symbols/Wild/Wild 26.png",
    slots10_26:  "/src/sprites/Symbols/Wild/Wild 27.png",
    slots10_27:  "/src/sprites/Symbols/Wild/Wild 28.png",
    slots10_28:  "/src/sprites/Symbols/Wild/Wild 29.png",
    slots10_29:  "/src/sprites/Symbols/Wild/Wild 30.png",
    slots10_30:  "/src/sprites/Symbols/Wild/Wild 31.png",
    slots10_31:  "/src/sprites/Symbols/Wild/Wild 32.png",
    slots10_32:  "/src/sprites/Symbols/Wild/Wild 33.png",
    slots10_33:  "/src/sprites/Symbols/Wild/Wild 34.png",
    slots10_34:  "/src/sprites/Symbols/Wild/Wild 35.png",
    slots10_35:  "/src/sprites/Symbols/Wild/Wild 36.png",


    slots12_0 :  "/src/sprites/Symbols/Jackpot/Jackpot 01.png",
    slots12_1 :  "/src/sprites/Symbols/Jackpot/Jackpot 02.png",
    slots12_2 :  "/src/sprites/Symbols/Jackpot/Jackpot 03.png",
    slots12_3 :  "/src/sprites/Symbols/Jackpot/Jackpot 04.png",
    slots12_4 :  "/src/sprites/Symbols/Jackpot/Jackpot 05.png",
    slots12_5 :  "/src/sprites/Symbols/Jackpot/Jackpot 06.png",
    slots12_6 :  "/src/sprites/Symbols/Jackpot/Jackpot 07.png",
    slots12_7 :  "/src/sprites/Symbols/Jackpot/Jackpot 08.png",
    slots12_8 :  "/src/sprites/Symbols/Jackpot/Jackpot 09.png",
    slots12_9 :  "/src/sprites/Symbols/Jackpot/Jackpot 10.png",
    slots12_10:  "/src/sprites/Symbols/Jackpot/Jackpot 11.png",
    slots12_11:  "/src/sprites/Symbols/Jackpot/Jackpot 12.png",
    slots12_12:  "/src/sprites/Symbols/Jackpot/Jackpot 13.png",
    slots12_13:  "/src/sprites/Symbols/Jackpot/Jackpot 14.png",
    slots12_14:  "/src/sprites/Symbols/Jackpot/Jackpot 15.png",
    slots12_15:  "/src/sprites/Symbols/Jackpot/Jackpot 16.png",
    slots12_16:  "/src/sprites/Symbols/Jackpot/Jackpot 17.png",
    slots12_17:  "/src/sprites/Symbols/Jackpot/Jackpot 18.png",
    slots12_18:  "/src/sprites/Symbols/Jackpot/Jackpot 19.png",
    slots12_19:  "/src/sprites/Symbols/Jackpot/Jackpot 20.png",
    slots12_20:  "/src/sprites/Symbols/Jackpot/Jackpot 21.png",
    slots12_21:  "/src/sprites/Symbols/Jackpot/Jackpot 22.png",
    slots12_22:  "/src/sprites/Symbols/Jackpot/Jackpot 23.png",
    slots12_23:  "/src/sprites/Symbols/Jackpot/Jackpot 24.png",
    slots12_24:  "/src/sprites/Symbols/Jackpot/Jackpot 25.png",
    slots12_25:  "/src/sprites/Symbols/Jackpot/Jackpot 26.png",
    slots12_26:  "/src/sprites/Symbols/Jackpot/Jackpot 27.png",
    slots12_27:  "/src/sprites/Symbols/Jackpot/Jackpot 28.png",
    slots12_28:  "/src/sprites/Symbols/Jackpot/Jackpot 29.png",
    slots12_29:  "/src/sprites/Symbols/Jackpot/Jackpot 30.png",
    slots12_30:  "/src/sprites/Symbols/Jackpot/Jackpot 31.png",
    slots12_31:  "/src/sprites/Symbols/Jackpot/Jackpot 32.png",
    slots12_32:  "/src/sprites/Symbols/Jackpot/Jackpot 33.png",
    slots12_33:  "/src/sprites/Symbols/Jackpot/Jackpot 34.png",
    slots12_34:  "/src/sprites/Symbols/Jackpot/Jackpot 35.png",
    slots12_35:  "/src/sprites/Symbols/Jackpot/Jackpot 36.png",
}



export const staticData = {
    // logoURL: "https://cccdn.b-cdn.net/1584464368856.png",
    // logoURL:  "/static/logo.png").default,
    Background:  "src/sprites/Background.jpg",
};

export const fontData = ["Montserrat"];



export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.wav",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.mp3",
        buttonpressed: "src/sounds/Game-Button.wav",
        spinWheelMusic: "src/sounds/spinWheel.mp3"
 
};

export const preloaderConfig = {
    // startLogo:  "/src/sprites/Logo.png")
}